"""Formatter for review comments and summaries."""
from datetime import datetime
from typing import Any, Dict, List


class ReviewFormatter:
    """Formats review results for GitHub comments."""

    @staticmethod
    def format_review_comment(review_result: Dict[str, Any], pr_info: Dict[str, Any], quick_warnings: List[str] = None) -> str:
        """
        Format review result into a GitHub comment.

        Args:
            review_result: Result from CodeAnalyzer
            pr_info: PR information
            quick_warnings: Quick check warnings

        Returns:
            Formatted markdown comment
        """
        summary = review_result.get("summary", "")
        critical_issues = review_result.get("critical_issues", [])
        suggestions = review_result.get("suggestions", [])
        inline_comments = review_result.get("inline_comments", [])

        # Header
        header = f"""# 🤖 AI Code Review

**PR:** #{pr_info['pr_number']} - {pr_info['pr_title']}
**Commit:** `{pr_info['head_sha'][:7]}`
**Reviewed at:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---
"""

        # Quick warnings section
        warnings_section = ""
        if quick_warnings:
            warnings_section = "\n## ⚡ Quick Checks\n\n"
            warnings_section += "\n".join(f"- {warning}" for warning in quick_warnings)
            warnings_section += "\n\n---\n"

        # Summary section
        summary_section = f"\n## 📋 Summary\n\n{summary}\n"

        # Critical issues section
        critical_section = ""
        if critical_issues:
            critical_section = "\n## 🚨 Critical Issues\n\n"
            critical_section += "\n".join(f"- {issue}" for issue in critical_issues)
            critical_section += "\n"

        # Suggestions section
        suggestions_section = ""
        if suggestions:
            suggestions_section = "\n## 💡 Suggestions\n\n"
            suggestions_section += "\n".join(f"{i+1}. {sug}" for i, sug in enumerate(suggestions))
            suggestions_section += "\n"

        # Inline comments notice
        inline_notice = ""
        if inline_comments:
            inline_notice = f"""

---

## 💬 Inline Comments

I've left **{len(inline_comments)} inline comment(s)** on specific lines of code.
Please check the "Files changed" tab to see them.
"""

        # Footer
        footer = """

---

<sub>🤖 This review was generated by MergeBlocker AI. It's meant to assist human reviewers,
not replace them. Please use your judgment when addressing these suggestions.</sub>
"""

        return header + warnings_section + summary_section + critical_section + suggestions_section + inline_notice + footer

    @staticmethod
    def format_error_comment(error_message: str, pr_info: Dict[str, Any]) -> str:
        """
        Format error message as a GitHub comment.

        Args:
            error_message: Error message
            pr_info: PR information

        Returns:
            Formatted error comment
        """
        return f"""# ❌ AI Code Review Error

**PR:** #{pr_info['pr_number']} - {pr_info['pr_title']}
**Commit:** `{pr_info['head_sha'][:7]}`

Unfortunately, the automated code review encountered an error:

```
{error_message}
```

**What to do:**
- Please review this PR manually
- Check if the PR size is within limits
- Contact the maintainer if this error persists

---

<sub>🤖 MergeBlocker AI</sub>
"""

    @staticmethod
    def format_skipped_comment(reason: str, pr_info: Dict[str, Any]) -> str:
        """
        Format skipped review message.

        Args:
            reason: Reason for skipping
            pr_info: PR information

        Returns:
            Formatted comment
        """
        return f"""# ℹ️ AI Code Review Skipped

**PR:** #{pr_info['pr_number']} - {pr_info['pr_title']}

This PR was not automatically reviewed because: {reason}

**To trigger a manual review:**
- Convert from draft to ready for review
- Or comment `/review` to force a review

---

<sub>🤖 MergeBlocker AI</sub>
"""

    @staticmethod
    def format_inline_comment(comment: Dict[str, Any]) -> str:
        """
        Format an inline comment for GitHub.

        Args:
            comment: Comment dict with 'body' key

        Returns:
            Formatted comment body
        """
        body = comment["body"]

        # Add AI badge
        return f"🤖 **AI Review**\n\n{body}"

    @staticmethod
    def format_check_run_summary(
        review_result: Dict[str, Any], pr_info: Dict[str, Any], quick_warnings: List[str] = None
    ) -> Dict[str, str]:
        """
        Format review result for GitHub Check Run.

        Args:
            review_result: Result from CodeAnalyzer
            pr_info: PR information
            quick_warnings: Quick check warnings

        Returns:
            Dictionary with 'title' and 'summary' keys
        """
        is_large = review_result.get("is_large_pr", False)
        inline_count = len(review_result.get("inline_comments", []))
        warnings_count = len(quick_warnings) if quick_warnings else 0

        # Determine title
        if is_large:
            title = "✅ Review Complete (Large PR - Summary Only)"
        elif warnings_count > 0:
            title = f"⚠️ Review Complete ({warnings_count} warning(s))"
        else:
            title = "✅ Review Complete"

        # Build summary
        summary_parts = [
            f"**PR:** #{pr_info['pr_number']} - {pr_info['pr_title']}",
            f"**Commit:** `{pr_info['head_sha'][:7]}`",
            "",
        ]

        if warnings_count > 0:
            summary_parts.append(f"**Warnings:** {warnings_count}")

        if inline_count > 0:
            summary_parts.append(f"**Inline Comments:** {inline_count}")

        summary_parts.extend(
            [
                "",
                "✅ AI code review completed successfully.",
                "",
                "Check the PR comments for detailed feedback.",
            ]
        )

        return {
            "title": title,
            "summary": "\n".join(summary_parts),
        }
